### ISSUE TITLE
Provide a more minimalistic cross-platform set of dependencies

### ISSUE THREAD

**Issue by holgerbrandl** [Leinadj/MEED-An-Unsupervised-Multi-Environment-EventDetector-for-Non-Intrusive-Load-Monitoring#16]
The current set of dependencies seems overly large given the actual dependencies of the provided implementation and does not easily allow for installation on a standard linux (python 3.7, latest anaconda) . 

Also, the provided requiremnts.txt does not install on Linux because some macos-specific dependencies are supported (e.g. `appscript`).

Other dependencies such as `xlwings` are windows/macos only as well and require special build tweaks so maybe the documentation could also provide some hints about the intended initial setup?

**Comment by holgerbrandl** [comment]
Given the size of the repo, it may be also helpful for the user if just one requirements.txt would be included and not 2 (root + Event_Detectors).

**Comment by Leinadj** [comment]
Thank's a lot! I generated a minimalistic requirements.txt using pipreqs https://github.com/bndr/pipreqs (nice tool by the way). The second one is removed too! Thanks for the feedback!
