### ISSUE TITLE
[Notebooks] Barsim_Sequential.ipynb: Loop stops too early

### ISSUE THREAD

**Issue by th3ragex** [Leinadj/MEED-An-Unsupervised-Multi-Environment-EventDetector-for-Non-Intrusive-Load-Monitoring#2]
Hi,

great repository. Thank you for making it easier to get into NILM!

I have just started checking out your example notebooks and found a minor issue:
Cell: Run the Event Detection on the Test Data

```python
while samples_remaining >= samples_raw_per_window_BLUED:
 [...]
     if found_event: 
          window_start = int(window_start + end_index) # set new starting point
      else:
          window_start = int(window_stop)
 
>>     samples_remaining -= samples_raw_per_window_BLUED <<
```
The last line assumes each window will progress by "samples_raw_per_window_BLUED" which is not the case if an event was found. This causes the loop to stop earlier than necessary.

Comparison:
Current version:
![image](https://user-images.githubusercontent.com/15040273/66586460-ec0f0e00-eb88-11e9-988f-b84b6039e730.png)

Expected:
![image](https://user-images.githubusercontent.com/15040273/66586472-f204ef00-eb88-11e9-90d7-da44a8a86789.png)

(red dots: labels, red lines: predictions,  yellow line: end of sliding window

Workaround:
```python
print("+++++++++++++++++++++++++++++++++++")
[...]
    if event_found:
        # We need to update the data points that remain for streaming now.
        window_start = int(window_start + end_index) # set new starting point
        samples_remaining -= end_index
        
    else: #no event was detected
        
        # We start at the end of the previous window
        window_start = int(window_stop)
        samples_remaining -= samples_raw_per_window_BLUED
```

**Comment by Leinadj** [comment]
Thanks, I have incorporated your hint!
