### ISSUE TITLE
MEED Paper - where to find

### ISSUE THREAD

**Issue by th3ragex** [Leinadj/MEED-An-Unsupervised-Multi-Environment-EventDetector-for-Non-Intrusive-Load-Monitoring#3]
Dear Mr Jorde and Mr Jacobsen,

the mentioned paper in the Readme of this repository does not seem to be publicly available. At least i am unable to find it (in google).

_Is there any chance to get access to it?_

I would love to give it a read since i am currently searching for a practical NILM solution.

**Comment by Leinadj** [comment]
A pre-liminary version is going to be presented end of october at the SmartGridComm conference.
The full work is going to be published soon afterward. As soon as this happens, I will notify you

**Comment by th3ragex** [comment]
@Leinadj Thank you very much. I wish you good luck with your talk!

**Comment by Leinadj** [comment]
Thanks!
