### ISSUE TITLE
[Notebooks] Liu_Ripple.ipynb: window_start_timestamp

### ISSUE THREAD

**Issue by th3ragex** [Leinadj/MEED-An-Unsupervised-Multi-Environment-EventDetector-for-Non-Intrusive-Load-Monitoring#4]
Hi,

The Liu_Ripple notebook as a small issue which causes strange event timestamps.

Cell: Run the Event Detection on the Test Data

```python
window_start_timestamp = file_info["file_start"] + timedelta(seconds=30) #first 30 seconds used for training
```

The offset of 30 seconds seems to be a copy paste left over from Jin.ipynb. 

After replacing this line with:
```python
window_start_timestamp = current_window.index[0]
```
the found events look reasonable. Before the resulting timestamps did not match the analyzed window.

before:
![image](https://user-images.githubusercontent.com/15040273/66642390-f1b63380-ec1c-11e9-9712-277f651cbf16.png)

after:
![image](https://user-images.githubusercontent.com/15040273/66642416-02ff4000-ec1d-11e9-948a-6c904b87fa0e.png)

**Comment by Leinadj** [comment]
Thanks, it should be resolved
